Modules
```{r}
library(ggplot2)
library(tsibble)
library(tseries)
library(MASS)
library(forecast)
library(TSA)
library(TTR)
library(aTSA)
library(graphics)
```

#Input data
```{r}
df=read.csv("marina_complete.csv")

sum(is.na(df))  #No missing value
```
#Exploration
##Plot entire dataset
```{r}
#Tugas: Forecast 6 jam terdepan

#Melihat sebaran seluruh ds
data.ts=ts(df$y)
plot(data.ts)
```

#Get the 7 latest days
```{r}
#Ambil 7 hari terakhir
temp=-(24*7)+length(data.ts)

sample=df[temp:length(data.ts),]

ts.sample=ts(sample$y)

```

#Check stationary
```{r}
#Check stationer
plot(ts.sample)    #Musiman

  #plot acf
acf(ts.sample)

  #plot pacf
pacf(ts.sample)

  #plot eacf
eacf(ts.sample)

  #Dickey-Fuller Test
adf.test(ts.sample)     #Stationer
```
#Train test split
```{r}
#Rendah ketika siang hari, tinggi ketika menjelang malam/subuh. Ada polanya.
#Buat test model beradasrkan 24 jam terakhir.
sample$ds=seq(length(sample$ds))
train=sample[1:(length(ts.sample)-24),]
test=sample[(length(ts.sample)-24+1):length(ts.sample),]

h=length(test$y)

sample.ts=ts(sample$y)
train.ts=ts(train$y)
test.ts=ts(test$y)
```
##Plot train test
```{r}
plot(train.ts, col="blue",main="Plot data train")
points(train.ts)

plot(test.ts, col="green",main="Plot data test")
points(test.ts)
```
#Model
```{r}
#We'll just use ARIMA since the data's stationary
model <- auto.arima(train.ts)
model

(fitted_model <- Arima(train.ts, order=c(3,0,3)))   #AIC = 818.85   
```
###Resisual Check
```{r}
sisaan.da = fitted_model$residuals 
par(mfrow=c(2,2)) 
qqnorm(sisaan.da) 
qqline(sisaan.da, col = "blue", lwd = 2) 
plot(c(1:length(sisaan.da)),sisaan.da) 
acf(sisaan.da) 
pacf(sisaan.da) 
par(mfrow = c(1,1))
```
###Formal Testing
```{r}
#1) Sisaan Menyebar Normal 
ks.test(sisaan.da,"pnorm")    #Tak tolak H0

#2) Sisaan saling bebas/tidak ada autokorelasi 
Box.test(sisaan.da, type = "Ljung")   #Tolak H0

#3) Sisaan homogen 
Box.test((sisaan.da)^2, type = "Ljung") #Tolak H0

#4) Nilai tengah sisaan sama dengan nol 
t.test(sisaan.da, mu = 0, conf.level = 0.95)    #Tolak H0
```
##Forecasting
```{r}
h=length(test.ts)
ramalan.da <- forecast::forecast(model, h = h) 
data.ramalan.da <- ramalan.da$mean
plot(ramalan.da)
```

```{r}
perbandingan.da<-matrix(c(test.ts, data.ramalan.da),
                     nrow = h, ncol = 2)
colnames(perbandingan.da)<-c("Aktual","Forecast")
perbandingan.da
accuracy(ts(data.ramalan.da), head(test.ts, n=h))
```

